#!/usr/bin/env bash

echo "
alias ..='cd ..'
alias ...='cd ../..'

alias h='cd ~'
alias c='clear'

alias ll='ls -l'
alias la='ls -la'

alias nrd='npm run dev'
alias nrw='npm run watch'
alias nrwp='npm run watch-poll'
alias nrh='npm run hot'
alias nrp='npm run production'

alias yrd='yarn run dev'
alias yrw='yarn run watch'
alias yrwp='yarn run watch-poll'
alias yrh='yarn run hot'
alias yrp='yarn run production'
" > /home/vagrant/.bash_aliases
